# Generated by Django 4.0.4 on 2022-07-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='date_of_message',
            field=models.DateField(auto_created=True, default='2022-07-20'),
            preserve_default=False,
        ),
    ]
