# Generated by Django 4.0.4 on 2022-07-26 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_directmessage_date_of_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='time_of_message',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='date_of_message',
            field=models.DateField(auto_now_add=True),
        ),
    ]
